name: Want
main: net.preoccupied.bukkit.want.WantPlugin
version: 0.2
author: obriencj@gmail.com
database: false
description: Grants stacks of items depending on permissions


commands:
  want:
    description: Grant yourself a stack of a given item
    usage: /want ITEM-NAME [COUNT]
    permission: preoccupied.want.item

  grant:
    description: Grants a player a stack of a given item
    usage: /grant PLAYER ITEM-NAME [COUNT]
    permission: preoccupied.want.grant

  item-search:
    description: Searches for items by name
    usage: /item-search PATTERN
    permission: preoccupied.want.info
    
  pack:
    description: Grants a player a pre-defined pack of items
    usage: /pack PLAYER PACK-NAME
    permission: preoccupied.want.pack

  pack-list:
    description: List packs by name, optionally matching a pattern
    usage: /pack-list [PATTERN]
    permission: preoccupied.want.info

  pack-info:
    description: Shows the information for the given pack
    usage: /pack-info PACK-NAME
    permission: preoccupied.want.info


permissions:
  preoccupied.want.admin:
    description: Admin rights
    default: op
    children:
      preoccupied.want.item: true
      preoccupied.want.pack: true
      preoccupied.want.grant: true
      preoccupied.want.info: true
      
      # the following are generated by the plugin at load time and are
      # populated with all of the item groups and packs
      preoccupied.want.item.*: true
      preoccupied.want.pack.*: true

  preoccupied.want.advanced:
    description: Advanced users
    default: false
    children:
      preoccupied.want.item: true
      preoccupied.want.pack: true
      preoccupied.want.grant: true
      preoccupied.want.info: true
      
      # the following are generated by the plugin at load time and are
      # populated with all of the item groups and packs
      preoccupied.want.item.*: true
      preoccupied.want.pack.*: true
      
  preoccupied.want.item:
    description: Ability to use the basic want command
    default: false

  preoccupied.want.pack:
    description: Ability to use the basic pack command
    default: false

  preoccupied.want.grant:
    description: Ability to use the grant command
    default: false

  preoccupied.want.info:
    description: Ability to search for items and packs
    default: false
    


# The end.
